travis:
  secure:
    BINSTAR_TOKEN: qSgU/NcT3/dcNSinSvR1jQGUA8pUcmyKn6LQ7B4sBY35s5TNI9CAq7zlm7NG++fFnQ5KRWpChRxuYjUOJ8nu5kH5ClpM34UWACQHWgby92Z3nikpFO3ewX5LcTq4QuNFp3VVoEk9PBJeKbuHIMB1w9nN88Bul8D50OrMfrYQmnFfWKUdWC3kZASfdGJbfRYUGWONr6jQiOnc06BT5NxQXXgwOGzilrRPkWk0+hlZg4d7Np2NQHg/p2U4szz79az47GIhzshQUY2xJgQzbGXQuBxLBK+WL6BYazZxmLcmThoeQqNW+Ye2TWwfklIDspGTIBSjtMy2do/tCQdPmQ3T3ZafVKh7cuZsIsA4xhoYAuieurMJTbQNUkfZxEewn4tYmaU07oPNFJW2E55K2VYr+AxWj/7h3bJMCuB74XEe86pe7hD+VDFk7Hw2N8a9fGD+xmI7u3+Z8IZoK4IiRtGNeywV6UhlyEOPM0qAYM9rHthqfxiJ+Yd1v92N1nNHuMJY6zw8b436saN7BUBlvlYFXiNknff7r1AhdNNlnvrcQhv90Wbk/NykTwqKF+z2K797saMtckYnLNHvl5HI7gRlMfM6G/0XJlUy1bqcvGiK5nSVWoSQ30shZMc1Tj9oBaCAz+5Sym9lwZY8rJqtGRmw73PLKp3MUquysJ+vyPrGLbU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
