travis:
  secure:
    BINSTAR_TOKEN: CqNOkP8VeNp+owBTB6Jrn903iV47bc9OoVPLPATpLP4c0RPM7Ujw+6L6+XhMeRAFnxvpzc3/NYaSHR32M3j2rLfXK4SvSNRSNiONcOarwFV6A+sFbg56BH879kpfs/00pSoYdlJVKzS8CHPV41JkbUDs9ckczP/NTYVV4o2H+Wnv80xqVAF9i5//5mAlladj/VXwUqsfRCOXCJzGNj0nijnpfYDqdG/DsPLILtsTliiEWQ/avHTKbqUa0dkcPYV9e+RLQvsVzhqnk45GXm5ftDI/aOdS+bhziq+NG/kGb1g+xO3/dN1Y4SweTJZB3h13eONS4gySIT4Oaq4rMAwbszn64nUe7N8sGcK8wp84mTZ5foA/vQQTJZ1XsKfVKHI9hU/eayLuXgRANGAu3chRBLpi9ch7XTEEcUympEMCJd1j0+tG95OrmxN3tjCmFYUPtuVk0EHikWwlDcZ+x9cCx9DcDakvw+xYdZpgH4/1ShZenwcLl8ThRiTa/gHWJ4AK0qdaBJfQ/FVsED5A5/AMSQZrYzRNl72B9lEKJWm/ZNNdLBLcJaeQh00dHwowPn0rUKs5+IRE3k9vYq3paAgYZPztvXkSstS+CmLWWLHL9irKNyN9W9ViHkL8KJxu/LPMjUy72stqiV7BBv9M7i2g/mdjXR3hcOGDyinFU2Jg7RU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
